@startuml
'https://plantuml.com/sequence-diagram

Actor User
participant Front
participant Catalog
participant Processing
participant Netflix
'System(Front,"Витрина")
'System(Catalog,"Каталог")
'System(Processing,"Операции")

== Получение данных для карточек ==
Netflix -> Catalog: данные для карточек
note right
GET host/v1/items
end note
== Заказ ЦТ ==
User -> Front
Front -> Catalog
Processing -> Catalog
Front -> Processing
Processing -> Netflix: GET host/v1/items/{item_id}/check
alt ЦТ доступен
Processing -> Front: 200 OK
Processing -> Netflix: PATCH host/v1/items/{item_id}/reserve
Processing -> Front: готов к оплате
User -> Front: Оплата
Front -> Processing: Оплата
Processing -> Netflix: PATCH host/v1/items/{item_id}/buy(паттерн Outbox)
else ЦТ отсутствует
Processing -> Front: 422 "Not avaliable"
end


@enduml